---
  # Install common packages and do basic configuration stuff

- name: Ensure Ubuntu VM is up-to-date
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600

- name: Install misc systems packages
  apt: name="{{ flaskapp_additional_app_packages }}"

- name: Install setfacl support
  apt: pkg=acl

- name: Ensure Ubuntu is up-to-date; install packages for the Flask app
  apt: name="{{ flaskapp_app_packages }}" state=latest

- name: Install the latest pip version
  pip: name=pip extra_args='-U'

- name: Ensure flask user
  user: name={{ flaskapp_app_user }} group={{ flaskapp_app_user }} createhome=no

- name: Ensure app directory
  file: dest={{ flaskapp_app_directory }} state=directory

- name: Ensure app log directory
  file: dest={{ flaskapp_app_log_directory }} state=directory
