---
# Install Postgresql

- name: Install required software packages for Postgresql
  apt: pkg="{{ flaskapp_postgresql_pkgs }}" state=latest
  notify: restart postgresql

- name: Create PgSQL database
  postgresql_db: name={{ flaskapp_postgresql_table }} encoding='UTF-8'
  become: true
  become_user: postgres

- name: Create a postgresql-user with access to the Database
  postgresql_user: db={{ flaskapp_postgresql_table }} name={{ flaskapp_postgresql_user }} password={{ flaskapp_postgresql_password }} priv=ALL
  become: true
  become_user: postgres

- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ flaskapp_postgresql_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: true
  become_user: postgres
